# Sensor
GAME_WINDOW_TITLE = "Super Hexagon"
GAME_WINDOW_WITHOUT_MARGIN = (11, 45, 778 - 11, 524 - 45)

EXPECTED_PLAYER_AREA = (1, 2, 3, 4)
SCREENSHOT_LOGGING_ENABLED = True
SAVED_SCREENSHOT_QUANTITY = 10

# Loop
MOVEMENT_ENABLED = True
